stages:
  - test
  - slither-analyzer

test:
  image: registry.gitlab.com/grassrootseconomics/cic-base-images/ci-solc-python:latest
  cache:
  - key:
      files:
        - requirements.txt 
        - test_requirements.txt
    paths:
      -  /root/.cache/pip 
  allow_failure: true
  script: 
    - cd python 
    - export PYTHONPATH=.
    - pip install --extra-index-url https://pip.grassrootseconomics.net:8433 
      --extra-index-url https://gitlab.com/api/v4/projects/27624814/packages/pypi/simple 
      -r requirements.txt -r test_requirements.txt 
    - bash run_tests.sh


slither-analize:
  image: registry.gitlab.com/grassrootseconomics/cic-base-images/ci-solc-python:latest
  script: 
    - pip install slither-analyzer 
    - slither solidity/
